---
title: "AnthonyS Fitbit Questions"
format: html
editor: visual
---

## Fitbit: Daily Data: Activity, Calories, Intensities,



```{r,echo=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)

```

## Import Fitbit Data

```{r,echo=FALSE}
rm(list=ls())
activity <- read_csv("./data/dailyActivity_merged.csv")
activity$ActivityDate <-  lubridate::mdy(activity$ActivityDate)
summary(activity)
```
```{r,echo=FALSE}
calories <- read_csv("./data/dailyCalories_merged.csv") |>  rename(ActivityDate = ActivityDay)
calories$ActivityDate <- mdy(calories$ActivityDate)
summary(calories)
```
```{r,echo=FALSE}
intensities <- read_csv("./data/dailyIntensities_merged.csv") |> rename(ActivityDate = ActivityDay)
intensities$ActivityDate <-  mdy(intensities$ActivityDate) 
summary(intensities)
```
```{r, echo=FALSE}
steps <- read_csv("./data/dailySteps_merged.csv") |> rename(ActivityDate = ActivityDay)
steps$ActivityDate <- mdy(steps$ActivityDate) 
summary(steps)
```

## Merge activity and calories data frames into one

```{r,echo=FALSE}

activity_calories <- activity |> inner_join(calories, by = c("ActivityDate", "Id")) |>
  inner_join(intensities, by = c("ActivityDate", "Id")) |>
  inner_join(steps, by = c("ActivityDate", "Id")) 
summary(activity_calories)
```